#!/bin/bash

case "$1" in
  start)
    /bin/bash /path/to/manage_my_process start
    ;;
  stop)
    /bin/bash /path/to/manage_my_process stop
    ;;
  restart)
    /bin/bash /path/to/manage_my_process stop
    /bin/bash /path/to/manage_my_process start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0